### ISSUE TITLE
Can a property of a class also be a class?

### ISSUE THREAD

**Issue by stijnbrysbaert** [stijnbrysbaert/OSLO-extension#1]
The 'Dock' class has a property 'capacity' that is a set of 'Capacity' classes. In this way a Dock can display the capacity of mulitple transport types.

Is this the right way?

**Comment by pietercolpaert** [comment]
I’m not sure what you mean with multiple transport types. Can you give an example of a dock with multiple modes?

**Comment by stijnbrysbaert** [comment]
Looking forward to Flanders ['Hoppin'-points](https://hoppin.be) there will be locations with multiple transport types available. For this I thought it was usefull to specify one dock with one geographic location but with multiple sorts of capacities, one for each transport type. In this way you only have one pointer/dock displayed on a map including multiple transport types.
On closer inspection it is may be more logic to limit a dock to only one transport type and then group one or more docks in a Hoppin-point.

**Comment by pietercolpaert** [comment]
I’d limit a dock to 1 transport type and then indeed group them together in a Hoppin point. I think that’s the nicest way forward!
